import type { MediaSlot } from './types';

/**
 * Central map of every image/video slot in the site to its placeholder asset.
 * Every entry here MUST also be logged in MEDIA-TODO.md at the repo root.
 * Swapping in real Instagram-sourced media later is a one-file change here.
 */
export const media: MediaSlot[] = [
  {
    id: 'home-hero-video',
    type: 'video',
    usage: 'Home hero background loop (all viewports — see HeroVideo)',
    placeholderPath: '/videos/home-hero-loop-v2.mp4',
    alt: 'Members training at Jaguar Fitness Den',
  },
  {
    id: 'home-hero-poster',
    type: 'image',
    usage: 'Home hero background poster (desktop background + mobile video fallback)',
    placeholderPath: '/images/hero/home-hero-poster.jpg',
    alt: 'A Jaguar Strength branded dumbbell in the foreground with the training floor blurred behind it',
  },
  {
    id: 'facilities-strip-equipment',
    type: 'image',
    usage: 'Home facilities strip — equipment photo',
    placeholderPath: '/images/facilities/strength-equipment.jpg',
    alt: 'The Jaguar Strength equipment floor, with a wide-arm pulldown machine in the foreground and the full machine row visible under hexagonal ceiling lighting',
  },
  {
    id: 'facilities-strip-group-studio',
    type: 'image',
    usage: 'Home facilities strip — group-class studio photo',
    placeholderPath: '/images/facilities/group-class-studio.jpg',
    alt: 'The group-class studio, with a full mirror wall and dramatic zigzag ceiling lighting',
  },
  {
    id: 'facilities-strip-lockers',
    type: 'image',
    usage: 'Home facilities strip — locker room photo',
    placeholderPath: '/images/facilities/locker-room.jpg',
    alt: 'The locker room, with wood-slat cubby storage and an arched, backlit doorway',
  },
  {
    id: 'facilities-strip-steam-room',
    type: 'image',
    usage: 'Home facilities strip — steam room photo',
    placeholderPath: '/images/placeholder/facilities-steam-room.jpg',
    alt: 'Steam room at Jaguar Fitness Den',
  },
  {
    id: 'facilities-strip-lounge',
    type: 'image',
    usage: "Home facilities strip — members' lounge photo",
    placeholderPath: '/images/placeholder/facilities-lounge.jpg',
    alt: "Members' lounge at Jaguar Fitness Den",
  },
  {
    id: 'program-strength',
    type: 'image',
    usage: 'Programs preview / detail — Strength Training',
    placeholderPath: '/images/placeholder/program-strength.jpg',
    alt: 'Member performing a strength training exercise',
  },
  {
    id: 'program-functional',
    type: 'image',
    usage: 'Programs preview / detail — Functional Training',
    placeholderPath: '/images/placeholder/program-functional.jpg',
    alt: 'Functional training circuit in progress',
  },
  {
    id: 'program-zumba',
    type: 'image',
    usage: 'Programs preview / detail — Zumba',
    placeholderPath: '/images/placeholder/program-zumba.jpg',
    alt: 'Zumba class in the group studio',
  },
  {
    id: 'program-yoga',
    type: 'image',
    usage: 'Programs preview / detail — Yoga',
    placeholderPath: '/images/placeholder/program-yoga.jpg',
    alt: 'Yoga session in the group studio',
  },
  {
    id: 'program-personal-training',
    type: 'image',
    usage: 'Programs preview / detail — Personal Training',
    placeholderPath: '/images/placeholder/program-personal-training.jpg',
    alt: 'Trainer coaching a member one-on-one',
  },
  {
    id: 'program-nutrition-coaching',
    type: 'image',
    usage: 'Programs preview / detail — Nutrition Coaching',
    placeholderPath: '/images/placeholder/program-nutrition-coaching.jpg',
    alt: 'Nutrition coaching consultation',
  },
  {
    id: 'member-app-home',
    type: 'image',
    usage: 'Home member-app highlight carousel — slide 1',
    placeholderPath: '/images/app-screens/member-app-home.jpg',
    alt: 'Members app home screen showing calories consumed and burnt, water, and weight tracking',
  },
  {
    id: 'member-app-workout-tracker',
    type: 'image',
    usage: 'Home member-app highlight carousel — slide 2',
    placeholderPath: '/images/app-screens/member-app-workout-tracker.jpg',
    alt: 'Members app workout tracker screen with weekly calendar and calorie burn calculator',
  },
  {
    id: 'member-app-water-intake',
    type: 'image',
    usage: 'Home member-app highlight carousel — slide 3',
    placeholderPath: '/images/app-screens/member-app-water-intake.jpg',
    alt: 'Members app water intake logging screen with quick-add bottle sizes',
  },
  {
    id: 'transformation-1',
    type: 'image',
    usage: 'Home transformations teaser — slide 1',
    placeholderPath: '/images/transformations/member-1-v3.jpg',
    alt: 'Member before-and-after transformation, story 1: from a slim starting point to a muscular, defined build',
  },
  {
    id: 'transformation-2',
    type: 'image',
    usage: 'Home transformations teaser — slide 2',
    placeholderPath: '/images/transformations/member-2-v3.jpg',
    alt: 'Member before-and-after transformation, story 2: significant weight loss and a leaner physique',
  },
  {
    id: 'transformation-3',
    type: 'image',
    usage: 'Home transformations teaser — slide 3',
    placeholderPath: '/images/placeholder/transformation-3.jpg',
    alt: 'Member transformation before and after, story 3',
  },
  {
    id: 'trainer-1',
    type: 'image',
    usage: 'Trainers page — placeholder headshot 1',
    placeholderPath: '/images/placeholder/trainer-1.jpg',
    alt: 'Placeholder trainer headshot 1',
  },
  {
    id: 'trainer-2',
    type: 'image',
    usage: 'Trainers page — placeholder headshot 2',
    placeholderPath: '/images/placeholder/trainer-2.jpg',
    alt: 'Placeholder trainer headshot 2',
  },
  {
    id: 'trainer-3',
    type: 'image',
    usage: 'Trainers page — placeholder headshot 3',
    placeholderPath: '/images/placeholder/trainer-3.jpg',
    alt: 'Placeholder trainer headshot 3',
  },
  {
    id: 'gallery-1',
    type: 'image',
    usage: 'Gallery page — slot 1',
    placeholderPath: '/images/placeholder/gallery-1.jpg',
    alt: 'Jaguar Fitness Den gallery photo 1',
  },
  {
    id: 'gallery-2',
    type: 'image',
    usage: 'Gallery page — slot 2',
    placeholderPath: '/images/placeholder/gallery-2.jpg',
    alt: 'Jaguar Fitness Den gallery photo 2',
  },
  {
    id: 'gallery-3',
    type: 'image',
    usage: 'Gallery page — slot 3',
    placeholderPath: '/images/placeholder/gallery-3.jpg',
    alt: 'Jaguar Fitness Den gallery photo 3',
  },
];
